Adds support for a Google Cloud SQL sidecar
treeverse/charts pull request #297
Opened 2024-11-27 12:59 UTC by oddeirikigland

closes #298

2024-11-27 12:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/treeverse/charts?pullRequest=297) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/treeverse/charts?pullRequest=297) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/treeverse/charts?pullRequest=297) it.</sub>

2024-11-27 13:46 UTC, itaiad200 commented
Hey @oddeirikigland , thank you for your contribution!
Do you mind opening an issue, explaining the motivation behind this change and link the issue to this PR?

2024-11-27 13:57 UTC, oddeirikigland commented
> Hey @oddeirikigland , thank you for your contribution! Do you mind opening an issue, explaining the motivation behind this change and link the issue to this PR?

Of course, added a short explanation now @itaiad200

2024-12-01 10:10 UTC, itaiad200 requested changes
Thank you for your contribution! Looks great. Few comments:
1. How was this tested?
2. Notice that the CI tests failed, please fix.
3. Notice the single comment on the `instances` attribute.

Please complete the above items, we'd very much like to merge this change 💪

2024-12-01 10:10 UTC, itaiad200 commented on charts/lakefs/README.md
> +| `gcpFallback.instances`           | The instances to connect to.
`instances` means there could be more than a single value right? How do you expect them to be passed?

2024-12-02 09:10 UTC, oddeirikigland commented on charts/lakefs/README.md
> +| `gcpFallback.instances`           | The instances to connect to.
The proxy supports several instances, that is why. One database instance is enough for this case, so I can change it to `instance` for simplification.  

I've tested it by adding a test file to the ci folder, enabling the gcpFallback with a path to my SQL instance in GCP. Also, I've used this setup for my self-hosted lakefs deployment in GCP. 

it would be great to have a `charts/lakefs/ci/gcp-fallback-values.yaml`, but then an open SQL gcp instance is needed. The config will then look as follows:

```yaml
gcpFallback:
  enabled: true
  instance: <my_project>:<my_region>:<my_instance>=tcp:5432
serviceAccount:
  name: <my_service_account>
```

2024-12-08 10:27 UTC, itaiad200 approved these changes
LGTM!

2024-12-08 10:27 UTC, merged