Add option to add additional labels to lakefs pod
treeverse/charts pull request #299
Opened 2024-12-05 10:06 UTC by wadhah101

2024-12-05 10:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/treeverse/charts?pullRequest=299) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/treeverse/charts?pullRequest=299) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/treeverse/charts?pullRequest=299) it.</sub>

2024-12-18 16:47 UTC, wadhah101 commented
@wadhah101 added description

2024-12-20 22:14 UTC, Isan-Rivkin requested changes
Thanks for drafting this. Please bump Chart.yaml

2024-12-23 09:00 UTC, wadhah101 commented
@Isan-Rivkin Bumped to 1.3.26

2024-12-23 13:27 UTC, Isan-Rivkin requested changes
First, thanks for drafting this PR! 

The issue with this change is that K8S does not allow duplicate keys in labels. 
Add a duplicate key such as `app` to `podLabels` yourself you'll see. 
For me it breaks when I add podLabel `app=duplicate` I run helm install with the error 

```sh
The Deployment "lakefs" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"duplicate", "app.kubernetes.io/instance":"lakefs", "app.kubernetes.io/name":"lakefs"}: `selector` does not match template `labels`
```
kubectl version (on EKS): 
```
Client Version: v1.29.0
Server Version: v1.30.7
```

So first, can you please better explain your use-case, is it specifically pod labels or Deployment labels? is it specifically override specific label keys? Should this affect the labelSelector? 
What is it you would like to achieve. 

Second incase of override label keys, I'd go with an override all-or-nothing approach not appending to existing labels.

2025-05-06 11:30 UTC, closed without merging

2025-05-06 11:30 UTC, itaiad200 commented
No activity